import type { Metadata } from "next"
import { WhatsAppLink } from "@/lib/whatsapp"
import ActiveBadge from "@/components/ui/ActiveBadge"
import JsonLd from "@/components/seo/JsonLd"
import { breadcrumbSchema, faqSchema, serviceSchema } from "@/lib/structured-data"
import { CheckItem } from "@/components/ui/CheckItem"

const wa = WhatsAppLink("Hola, quiero consultar sobre publicidad online")

export const metadata: Metadata = {
  title: "Google Ads y SEO para Pymes | Publicidad Online | Página Web Arg",
  description: "Gestionamos Google Ads y SEO para que tu negocio aparezca primero. Campañas con seguimiento real de resultados y optimización mensual.",
  alternates: { canonical: "https://www.paginawebarg.com.ar/publicidad" },
}

const adsIncludes = ["Configuración de campaña de búsqueda", "Investigación de keywords del rubro", "Redacción de anuncios", "Configuración de conversiones (llamadas, formularios, WhatsApp)", "Optimización mensual", "Reporte de resultados"]
const seoIncludes = ["Auditoría técnica SEO del sitio", "Investigación de keywords", "Optimización on-page (títulos, metas, estructura)", "Mejoras de velocidad y Core Web Vitals", "Estrategia de contenidos", "Seguimiento de posiciones"]
const adsSteps = [["01", "Investigación y estrategia", "Analizamos tu rubro, tu competencia y las keywords que busca tu cliente ideal. Definimos el presupuesto, las pujas y la estructura de campaña."], ["02", "Configuración y lanzamiento", "Creamos los grupos de anuncios, redactamos los textos, configuramos las extensiones y el seguimiento de conversiones."], ["03", "Optimización continua", "Revisamos el rendimiento semanalmente: ajustamos pujas, pausamos keywords que no convierten y escalamos las que funcionan."], ["04", "Reporte mensual", "Te enviamos un reporte claro con impresiones, clics, conversiones y costo por resultado. Nada de métricas vacías."]]
const seoItems = [["Auditoría técnica", "Revisamos velocidad, estructura de URLs, indexación, errores crawl, Core Web Vitals y todo lo que afecta como Google ve tu web."], ["Keyword research", "Identificamos que buscan tus clientes potenciales, qué volumen tienen esas búsquedas y qué tan difícil es posicionar para cada una."], ["Optimización on-page", "Titles, meta descriptions, H1, H2, contenido, alt de imágenes, datos estructurados. Cada página optimizada para posicionar."], ["Velocidad y Core Web Vitals", "Google premia los sitios rápidos. Optimizamos carga, LCP, CLS y FID para cumplir los estándares que el algoritmo exige."], ["Estrategia de contenidos", "Creamos o mejoramos el contenido de tu web para responder las preguntas que hace tu cliente ideal y posicionar en esas búsquedas."], ["Seguimiento mensual", "Reportes de posiciones, tráfico orgánico y evolución. Transparencia total en cada etapa del trabajo."]]
const crm = [["Cada lead de la campaña queda registrado", "Ya sea que contacte por el formulario de la web o directo al WhatsApp desde el anuncio, el CRM lo captura automáticamente."], ["Sabés qué anuncio trajo cada cliente", "Con el seguimiento de conversiones de Google Ads más el CRM, podés rastrear exactamente qué keyword, qué anuncio y qué campaña generó cada cliente real."], ["El vendedor no pierde ningún lead", "Asignamos el lead al agente de ventas correspondiente. El CRM muestra cuáles están sin respuesta y hace recordatorios de seguimiento."]]
const faqs = [["¿Cuánto necesito invertir en Google Ads para ver resultados?", "Depende del rubro y la competencia. Para negocios locales, campañas desde $200-300 USD mensuales de presupuesto publicitario pueden generar resultados. Nuestra gestión se cobra aparte."], ["¿Cuánto tarda el SEO en dar resultados?", "Los primeros movimientos se ven entre 2 y 4 meses. Resultados sólidos y sostenidos, entre 6 y 12 meses. El SEO es una inversión a largo plazo."], ["¿Gestionan el presupuesto de Google o solo la configuración?", "Gestionamos todo: la estrategia, la configuración, la optimización mensual y los reportes. El presupuesto publicitario lo cargás directamente en tu cuenta de Google Ads."], ["¿Puedo combinar Google Ads y SEO?", "Sí, y es lo más recomendable. Ads da resultados inmediatos mientras el SEO crece. Con el tiempo, si el SEO posiciona bien, podés reducir la inversión en Ads."], ["¿El CRM tiene costo adicional?", "Sí. La integración del CRM para gestión de leads se cotiza aparte."]]

export default function PublicidadPage() {
  return (
    <>
      <section className="hero-bg hero-bg-publicidad site-hero text-center"><div className="section-wrapper"><ActiveBadge text="Resultados medibles desde el primer día" /><h1 className="mx-auto mt-6 max-w-4xl text-4xl font-bold md:text-6xl">Más clientes para tu negocio, desde Google</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-text-secondary">Gestionamos tu publicidad en Google Ads y optimizamos tu posicionamiento orgánico con SEO. Resultados medibles desde el primer día.</p><a href={wa} target="_blank" rel="noopener noreferrer" className="btn-primary mt-10">Consultar por WhatsApp</a></div></section>
      <section className="bg-navy-light py-20"><div className="section-wrapper"><h2 className="text-center text-3xl font-bold md:text-5xl">Dos caminos para conseguir más clientes</h2><div className="mt-12 grid gap-6 lg:grid-cols-2"><article className="card"><span className="rounded-full bg-brand-orange/20 px-3 py-1 text-xs font-bold text-brand-orange">Google Ads</span><h3 className="mt-4 text-2xl font-bold">Google Ads - Resultados inmediatos</h3><p className="mt-3 leading-7 text-text-secondary">Tu negocio aparece en los primeros resultados de Google cuando alguien busca exactamente lo que ofrecés. Pagás solo cuando alguien hace clic en tu anuncio.</p><div className="mt-5 grid gap-3">{adsIncludes.map((item) => <CheckItem key={item} text={item} />)}</div><a href={wa} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex font-semibold text-brand-orange transition hover:text-orange-400">Consultar Google Ads</a></article><article className="card"><span className="rounded-full bg-brand-green/20 px-3 py-1 text-xs font-bold text-brand-green">SEO</span><h3 className="mt-4 text-2xl font-bold">SEO - Resultados a largo plazo</h3><p className="mt-3 leading-7 text-text-secondary">Optimizamos tu web para que Google la posicione en los primeros resultados de manera orgánica, sin pagar por cada clic. Una inversión que crece con el tiempo.</p><div className="mt-5 grid gap-3">{seoIncludes.map((item) => <CheckItem key={item} text={item} />)}</div><a href={wa} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex font-semibold text-brand-green transition hover:text-green-400">Consultar SEO</a></article></div></div></section>
      <section id="ads" className="bg-navy py-20"><div className="section-wrapper"><h2 className="text-center text-3xl font-bold md:text-5xl">Cómo gestionamos tus campañas de Google Ads</h2><p className="mx-auto mt-5 max-w-3xl text-center text-text-secondary">No solo creamos el anuncio y lo dejamos correr. Gestionamos la campaña activamente para que cada peso invertido genere el máximo retorno.</p><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{adsSteps.map(([n, h, t]) => <article key={n} className="card"><p className="text-4xl font-bold text-brand-blue">{n}</p><h3 className="mt-4 text-xl font-bold">{h}</h3><p className="mt-3 leading-7 text-text-secondary">{t}</p></article>)}</div></div></section>
      <section id="seo" className="bg-navy-light py-20"><div className="section-wrapper"><h2 className="text-center text-3xl font-bold md:text-5xl">Cómo trabajamos el SEO de tu web</h2><p className="mx-auto mt-5 max-w-3xl text-center text-text-secondary">El SEO no es magia ni promesas de resultados instantáneos. Es trabajo técnico constante que posiciona tu web de manera sostenida.</p><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{seoItems.map(([h, t]) => <article key={h} className="card"><h3 className="text-xl font-bold">{h}</h3><p className="mt-3 leading-7 text-text-secondary">{t}</p></article>)}</div></div></section>
      <section className="bg-navy py-20"><div className="section-wrapper"><span className="rounded-full border border-brand-blue bg-brand-blue/15 px-4 py-2 text-xs font-bold text-brand-blue">CRM + WHATSAPP</span><h2 className="mt-6 text-center text-3xl font-bold md:text-5xl">Las campañas traen leads - el CRM los convierte en clientes</h2><p className="mx-auto mt-6 max-w-4xl text-center leading-7 text-text-secondary">De nada sirve que Google Ads genere consultas si no tenés un sistema para gestionarlas. Integramos un CRM conectado a WhatsApp para que cada lead que llega de tus campañas quede registrado y con seguimiento hasta el cierre.</p><div className="mt-10 grid gap-6 md:grid-cols-3">{crm.map(([h, t]) => <article key={h} className="card"><h3 className="text-xl font-bold">{h}</h3><p className="mt-3 leading-7 text-text-secondary">{t}</p></article>)}</div><aside className="mt-8 rounded-lg border-l-4 border-brand-blue bg-slate-card p-5 text-text-secondary">La integración del CRM es un servicio adicional que cotizamos aparte. Trabajamos con HubSpot, Kommo y Pipedrive.</aside></div></section>
      <section className="bg-navy-light py-20"><div className="section-wrapper"><div className="grid gap-6 text-center md:grid-cols-3"><article className="card"><p className="text-4xl font-bold text-brand-blue">100%</p><p className="mt-2 text-text-secondary">proyectos entregados</p></article><article className="card"><p className="text-4xl font-bold text-brand-blue">Google</p><p className="mt-2 text-text-secondary">Partner certificado</p></article><article className="card"><p className="text-4xl font-bold text-brand-blue">SEMrush</p><p className="mt-2 text-text-secondary">Certificación SEO activa</p></article></div></div></section>
      <section className="bg-navy py-20"><div className="section-wrapper max-w-4xl"><h2 className="text-center text-3xl font-bold md:text-5xl">Preguntas frecuentes</h2><div className="mt-10 divide-y divide-slate-card">{faqs.map(([q, a]) => <details key={q} className="py-5"><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-3 leading-7 text-text-secondary">{a}</p></details>)}</div></div></section>
      <section className="bg-graphite py-24 text-center"><h2 className="text-3xl font-bold text-white md:text-5xl">Más clientes para tu negocio, empezando hoy</h2><p className="mt-5 text-cream/70">Te contamos qué estrategia es la más conveniente para tu caso.</p><a href={wa} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex rounded-[4px] bg-orange px-8 py-4 font-semibold text-white transition-all duration-300 hover:bg-orange-hover hover:scale-[1.02]">Consultar por WhatsApp</a></section>
          
            <JsonLd data={serviceSchema("Google Ads y SEO para Pymes", "Gestionamos Google Ads y SEO para que tu negocio aparezca primero. Campañas con seguimiento real de resultados y optimización mensual.", "/publicidad")} />
      <JsonLd data={faqSchema(faqs)} />
                  <JsonLd data={breadcrumbSchema([
        { name: "Inicio", item: "https://www.paginawebarg.com.ar" },
        { name: "Publicidad Online", item: "https://www.paginawebarg.com.ar/publicidad" },
      ])} />
    </>
  )
}








